### PR TITLE
Add | New | iOS Dev Weekly 455

### PR DESCRIPTION
**Pull request by irshadpc**

### CODE REVIEW

**Comment by irshadpc** [comment]
@pedrommcarrasco, Please review.

**Comment by irshadpc** [comment]
> Thank you @irshadpc!
> 
> One minor thing: every time you open a PR assign me as a reviewer (on the right side of your screen). In that way it will appear [here](https://github.com/pulls) for me

@pedrommcarrasco, I know that feature and somehow it won't appear on my screen.

**Comment by pedrommcarrasco** [comment]
Oh, that's weird. It never appears or it's just on this repo?

**Comment by pedrommcarrasco** [comment]
Anyway, added a bot to this repo for this. Let's hope it works 😂

**Pull request merged**
