### PR TITLE
Add | Event | mDevCamp 2020

### PR DESCRIPTION
**Pull request by tomassliz**

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Thank you for adding this event 👍 
I've updated the logo but I'm having some troubles opening its website, it seems to be down to me 🤔

**Comment by tomassliz** [comment]
It's weird, I'm trying open the website and it's working for me:

Screenshot 2020-02-29 at 17 34 16

**Comment by tomassliz** [comment]
@pedrommcarrasco Can you try it again please? If it doesn’t work I will contact the organizer. From which country do you try to open the website please?

**Comment by pedrommcarrasco** [comment]
Tried again and I still can't open it. I'm trying from Portugal and the provider is Vodafone.

**Comment by pedrommcarrasco** [comment]
You're right @tomassliz, my bad 💯 
Website seems to be loading now!

**Pull request merged**
