### PR TITLE
Add | New | 1) Capture Lists, 2) Protocol-Oriented Programming

### PR DESCRIPTION
**Pull request by scotteg**
Added two new articles:

1. **Capture Lists** - in this article I explain capture lists and how to use them effectively. I also explain value vs. reference types, strong reference cycles, and escaping vs. nonescaping closures.
1. **Protocol-Oriented Programming** - in this article I explain protocol-oriented-programming and how to use protocols to define requirements and provide default implementations. I also explain how to determine if a protocol member will be statically or dynamically dispatched.

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Hello @scotteg 👋
Happy to see you here and congrats on the new job! 🎉 

I'll have to close this pull request as this is not the way you should submit articles for CocoaHub's editions. I'm aware that this repo might be lacking some documentation and I'll tackle this as soon as possible. For now, I'll explain it here 👇 

Every week we open an issue on GitHub where people can submit articles (even if they were the authors) and this "gathering" phase lasts Friday. 
On Friday, we selected the best ones and we then push them to our database so everyone can read them (and we also send a push notification informing that a new edition is available).

This said and as an example, you (or anyone else) should've submitted your latest, article **Protocol-Oriented Programming**, on [last week's submissions issue](https://github.com/pedrommcarrasco/CocoaHub.content/issues/91).

However, given an well written and good your latest article is, I'll be opening an exception and push **Protocol-Oriented Programming** to our latest edition.

Let me know if you have any question and sorry for not having this properly documented 😅

tl-dr: Here's what you have to do every time you want to submit an article:
- open this [link](https://github.com/pedrommcarrasco/CocoaHub.content/issues) 
- open Edition #X Submissions
- Leave a link to your article (title and description are optional) as a comment

**Comment by pedrommcarrasco** [comment]
As promised 👇 
IMG_7307

**Comment by scotteg** [comment]
@pedrommcarrasco Thanks so much for explaining the protocol, and for including my article. And for the congrats—I'm stoked to join the  dev pub team.

**Comment by scotteg** [comment]
@pedrommcarrasco Should I submit my other article in a future edition?

**Comment by pedrommcarrasco** [comment]
>  And for the congrats—I'm stoked to join the  dev pub team.

That's an awesome achievement and you'll definitely have a lot of work to do! 🥇 

**⚠️  Feel free to ignore this question if you don't want to answer it or if it goes against any protocol from your future employee**
Do you think you'll keep writing articles on your own?

**Comment by pedrommcarrasco** [comment]
> Should I submit my other article in a future edition?

Unfortunately we'll have to skip your article on **Capture Lists** due to its release date 😢

If you look closely at the upcoming edition that closes on Friday (https://github.com/pedrommcarrasco/CocoaHub.content/issues/93) you'll notice it says:  _"Only articles from April 24 to May 1."_. Every edition should only have articles published in that edition's week, so in order to have your future articles published on CocoaHub, here's what you could do:

- Publish an article
- During the week in which you published an article, check this repo and the currently open "Edition X Submissions" issue
- Post it there 👍 

Questions?

**Pull request closed without merging**
