### PR TITLE
Add | New | Added Practical Combine book announcement

### PR DESCRIPTION
**Pull request by donnywals**
Not sure if it's okay to add this as news since it's my own book that I'm selling. I didn't see anything obvious in the rules that would prohibit this so I figured I'd give it a shot.

Cheers!

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Unfortunately sharing content that's behind a paywall is something we don't do. I'm sorry to tell you @donnywals but I'll have to close this Pull-Request. I bought the book, it looks great but I would go against the rules if I accepted this.

We'll definitely have a way of promoting paid content in the future but right now that's not yet implemented.

Sorry 😞

**Comment by donnywals** [comment]
No problem Pedro! I was pretty sure you'd end up closing it when I made the PR but I figured I'd give it a shot anyway because I didn't see any explicit rules that say it's not allowed. 👍🏼

**Comment by pedrommcarrasco** [comment]
Yeah, I really need to spend some time updating the documentation here... 😞

**Comment by donnywals** [comment]
No worries 😊 if I find time later today I might submit a PR for the contributing page to add something along the lines of payed content not being appropriate 👍🏼

**Comment by pedrommcarrasco** [comment]
That would be awesome, thank you Donny! ❤️

**Pull request closed without merging**
